//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tasks
    {
        public int task_id { get; set; }
        public int request_id { get; set; }
        public int employee_id { get; set; }
        public string task_desctiprion { get; set; }
        public Nullable<System.DateTime> deadline { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Request Request { get; set; }
    }
}
